version: '3.8'

services:
  # Frontend development server
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-builder
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    profiles:
      - dev

  # Backend API server
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "8000:8000"
    volumes:
      - ./apps/ai-services:/app/ai-services
      - ./plugins/mix-muse:/app/plugins/mix-muse
    environment:
      - PYTHONPATH=/app
    command: python3 main.py
    profiles:
      - dev

  # Production build
  production:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "8000:8000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  # Development with hot reload
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "cd /app/backend && python3 main.py & cd /app && npm run dev"
    profiles:
      - dev

networks:
  default:
    name: mixcode-network 